.github/workflows/ci.yaml

Without this patch, a single failure stops all the build.
It might be useful to know more about all the issues, instead of
just one.
This fixes it by ensuring the matrix is not stopped early if
a problem with a language happens.

Do not fail fast if a language container failed

---

.github/workflows/ci.yaml
tox.ini

Without this, one needs to enter the venv to run specific command
that are installed through setuptools entrypoints.
This is mildly annoying.
This fixes it by introducing a 'venv' environment, whose purpose
is only to accept commands.

Add venv for commands

---

.github/workflows/container-scan.yaml

This doesn't bring us anything, as we are not building/publishing
images here. This is just a tool to report state, and therefore
can be only used in periodics.
This should fix it, and make our PRs cleaner.

Disable vulnerability checkers on pushs and PRs

---

README.md
test_node.py

Without this, documentation seems intertwined in the test_node
file, where the documentation should be complete in the README
instead.
This should fix it.
At the same time, I am cleaning up so that black is happy.

Cleanup the test_node file

---

matryoshka_tester/helpers.py

Without this patch, we try to instantiate PODMAN_RUNTIME at all
times.
This is a problem, as some user might not have PODMAN, and the
program will crash with a Runtime Error.
This fixes it by only instantiating a podman runtime if it's
worth it.

Allow to run tooling without podman

---

test_node.py

The async package ocasionaly fails to test, but often enough to make the CI flaky.

Remove async from test_node

---

conftest.py
matryoshka_tester/helpers.py
test_go.py
test_multistage.py
test_node.py

We have a lot of tests that are essentially just `git clone $url && cd basename($url) && $build_cmd` but implemented in different places. To reduce code duplication, we add a new fixture `git_clone`, that executes the correct git clone (supporting tags as well) inside the container and returns the test parameters.
This allows us to reuse some common datastructures from the `ContainerBuild` class as well.

Unify the tests that clone git repositories

---

test_node.py

Without this, node tests break.
This is a problem, as we are making those mandatory.
This fixes it by marking the test as _expected failure_ instead
of skipped, so that we can track when it's working again, and
re-enable it.

Mark the visionmedia/debug build as failure

---

conftest.py
matryoshka_tester/data/containers.json
matryoshka_tester/fips.py
test_base.py
test_unit.py
tox.ini

This is based on the latest data structure refactor (and therefore needs rebase when it's merged).
This tests the base container, including its openssl behaviour on FIPS and non FIPS hosts.

Test base container and its openssl behaviour

---

test_base.py

Without this, the assertion fails, because the error message
appears on stderr, not stdout.
This fixes the FIPS tests.

Not a known digest is in stderr

---

.github/workflows/ci.yaml
.github/workflows/container-scan.yaml
matryoshka_tester/parse_data.py
matryoshka_tester/trigger_test.py
setup.cfg
test_unit.py
tox.ini

This PR is based on #39: it adds a new entry point that listens to rabbit.opensuse.org and launches the CI pipeline every time the repositories get published.

Rabbitmq trigger

---

.github/workflows/ci.yaml
.github/workflows/container-scan.yaml
tox.ini

Without this, the container-scan is incorrectly having the version
instead of the URL to test.
This is a problem, as it will prevent those tests to run correctly.
This fixes it by simplifying the stringified_matrix generation,
adapting to the right filed.
Next to this, the ci is using tox, but we have established a list
of what we test inside the CI that's not matching tox, for
simplicity.
Because we are having more and more tests, I simplified so that
the CI is matching tox envlist. Extra environments won't be
tested, as it is done currently.

Fix and simplify CI

---

matryoshka_tester/helpers.py
test_base.py
test_go.py

Without this, we don't ensure any size of containers.
This is a first step, tackling the decompressed size,
until we have other tests to tackle the compressed
size present in the registry.

Add a way to test decompressed size of containers

---

test_base.py

Because of size for minimum runtime containers, we want to
remove as much as possible from base.

Ensure base images don't contain grep

---

matryoshka_tester/helpers.py

We were previously not reusing cached layers, which makes test runs slower (at least locally).

Use buildah bud --layers to build images with buildah

---

test_init.py

This fixes https://github.com/SUSE/BCI-tests/issues/69

Add check that systemd is not present in non-init containers

---

bci_tester/data.py
tox.ini

`typing.Literal` is available after python3.8, and openQA
tests with "old" hosts are using python3.6.

import Literal from typing_extensions for python 3.6

---

bci_tester/data.py
tests/test_all.py
tests/test_metadata.py
tests/test_minimal.py

Reason: `tox -e all -- -n auto -k bci/bci-busybox_15.4` fails with no test runs.

Add BUSYBOX_CONTAINER to CONTAINERS_WITHOUT_ZYPPER

---

conftest.py
tests/test_minimal.py

Currently we are completely blind to the size increases as the minimal image size check has been gated by an xfail.

Remove xfail in minimal image size check

---

tests/test_python.py

Progress [111164](https://progress.opensuse.org/issues/111164).
Issue RC:
the test webserver_1, when docker is used, after started the [http server process in background](https://github.com/SUSE/BCI-tests/blob/ad66bd802a09f2a1d4a5184e81c96844bdc45d6b/tests/test_python.py#L129) with testinfra run, the next testinfra socket check loop resulted in pause until the server process end. Therefore only applying a timeout to that process, the socket check will return a value after the timeout
- Local test run,used podman: PASS
tox -e python
See result in: http://pasta.qam.suse.de/S1rXQYmt
- openQA run used docker : PASS
clone_job.pl --from openqa.suse.de --skip-chained-deps --skip-download 8770672 BCI_TESTS_REPO=https://github.com/m-dati/bci-tests.git BCI_TESTS_BRANCH=python_ws1 QEMUCPU=host …

BCI python test_webserver_1 issue fix

---

bci_tester/data.py
pyproject.toml
tests/test_metadata.py
tests/test_pcp.py
tox.ini

This follows the init tests, as the pcp container is based on the
init container. The docker test is removed as only podman is supported.
WIP
export TARGET=x
export BASEURL=registry.suse.de/home/doreilly/branches/suse/sle-15-sp4/update/bci
tox -e pcp

Add pcp tests

---

bci_tester/data.py

It was removed by accident in https://github.com/SUSE/BCI-tests/pull/130

Bugfix init container: restore default_entry_point=True

---

tests/test_go.py

Add a test run for go generics on go 1.18 containers.
Related issue: https://github.com/SUSE/BCI-tests/issues/118

Add generics test for go 1.18

---

tests/test_python.py

an Issue was found in the test_python - test_webserver_1 that was related to the hdd_1 qcow2 having an old podman version 1.x.x.
Here the VR:
http://marvin5.arch.suse.cz/tests/229  # sles es 8.5, regression podman.v.4x: `PASS`
http://marvin5.arch.suse.cz/tests/228  # sles es 7.9, fix podman.v.1x: `PASS`!

Bci python webserver_1 fix for podman old version

---

tests/test_repository.py

This should fix the repository tests that have been broken for a while now

Add additional packages to REPOCLOSURE_FALSE_POSITIVES

---

tests/test_metadata.py

The container metadata tests were failing due to some long standing issues, mostly with the labels of the application stack BCIs. This pull request addresses those issues.

Fix metadata tests

---

.github/workflows/ci.yaml

The lint & doc tox targets were accidentally included in the test matrix and
created for each container runtime and each OS version, which makes no sense at
all. The sed call in the test matrix generation simply needs adjusting to
exclude these two environments that are run separately already.

Fix the test matrix generation: exclude lint & doc

---

.github/workflows/ci.yaml

This environment variable is only useful when running `tox --parallel`, which we don't.

Remove pointless env var TOX_PARALLEL_NO_SPINNER from ci.yaml

---

tests/test_init.py

Improve the systemd tests for the bci-init container by adding multiple
new tests for boottime, journald, timedatectl, loginctl, hostnamectl.
Related ticket: https://progress.opensuse.org/issues/111054

Improve bci-init tests

---

tests/test_init.py

It fails sometimes in ARM: https://openqa.suse.de/tests/9048340#step/init/1
Verification run with 5.5s: https://openqa.suse.de/tests/9057206

Increase boottimes for init container

---

tests/test_metadata.py

The .Net containers only get build for x86_64, thus we cannot add them to the
metadata tests as they otherwise cause the assertion:
```
assert len(ALL_CONTAINERS) == len(
IMAGES_AND_NAMES
), "IMAGES_AND_NAMES must have all containers from BASE_CONTAINERS"
```
to fail.

Only add .Net containers to metadata tests on x86_64

---

tests/test_python.py

To avoid things like https://bugzilla.suse.com/show_bug.cgi?id=1201261
Python 3.6: http://marvin5.arch.suse.cz/tests/705#step/python/4
Python 3.9: http://marvin5.arch.suse.cz/tests/706#step/python/4
Python 3.10:http://marvin5.arch.suse.cz/tests/704#step/python/4

Add python_devel pkg installation test

---

tests/test_base.py

After trying to enable bci tests for base image, I found the following errors:
aarch64:
```
>       assert (
container_runtime.get_image_size(auto_container.image_url_or_id)
< BASE_CONTAINER_MAX_SIZE[LOCALHOST.system_info.arch] * 1024 * 1024
)
E       AssertionError: assert 137972672.0 < ((130 * 1024) * 1024)
```
s390x:
```
>       assert (
container_runtime.get_image_size(auto_container.image_url_or_id)
< BASE_CONTAINER_MAX_SIZE[LOCALHOST.system_info.arch] * 1024 * 1024
)
E       AssertionError: assert 160373180.0 < ((150 * 1024) * 1024)
```

Increase max size for BCI base for aarch64 and ppc64le

---

tests/test_base.py

With old podman versions, the output of `openssl gost` command is:
```
podman exec 9e /bin/sh -c 'openssl gost /dev/null'
gost is not a known digest
Error: non zero exit code: 1: OCI runtime error
```
instead of just
```
podman exec 9e /bin/sh -c 'openssl gost /dev/null'
gost is not a known digest
```
with newer podman versions.
So, it contains some additional text, and the assertion fails
because we are only expecting "gost is not a known digest".
By doing it as I'm proposing, we cover both cases.

Run openssl gost output less strict

---

tests/test_base.py

Error on s390x:
```
>       assert (
container_runtime.get_image_size(auto_container.image_url_or_id)
< BASE_CONTAINER_MAX_SIZE[LOCALHOST.system_info.arch] * 1024 * 1024
)
E       AssertionError: assert 128462272.0 < ((120 * 1024) * 1024)
```
e.g. https://openqa.suse.de/tests/9188890#step/base/1
VR: http://openqa.suse.de/t9197006

Increase Base Image max size to 125 for s390x

---

tests/test_base.py

error: https://openqa.suse.de/tests/9196759#step/base/1
```
>       assert (
container_runtime.get_image_size(auto_container.image_url_or_id)
< BASE_CONTAINER_MAX_SIZE[LOCALHOST.system_info.arch] * 1024 * 1024
)
E       AssertionError: assert 141679558.0 < ((135 * 1024) * 1024)
```
VR: http://openqa.suse.de/t9197854

Increase Base Image max size to 140 for aarch64

---

bci_tester/util.py
conftest.py
tests/test_go.py

Related ticket: https://progress.opensuse.org/issues/117373

Install dapper via download for go < 1.17 and don't build rancher on ppc64

---

bci_tester/data.py

This should prevent healthcheck timeouts on slow aarch64 & s390x workers

Increase healthcheck_timeout for 389ds, pcp & init to 240s

---

tests/test_init.py

Occasional timeouts on our aarch64 workers suggests that we should increase the STARTUP time limit for those workers.
* Related ticket: https://progress.opensuse.org/issues/119611
* Related failures: https://openqa.suse.de/tests/9843206 (8 failures)
* VR: https://openqa.suse.de/tests/9843043

Increase boottime for aarch64 workers

---

tests/test_openjdk.py

https://progress.opensuse.org/issues/119344
VR: 
- PPC http://openqa.suse.de/tests/9927798
- X86 http://openqa.suse.de/tests/9927803
~Needs: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15891~

Skip cassandra in case of PPC architecture

---

.github/workflows/ci.yaml

The podman builds are now failing because the registries.d directory no longer exists. install podman explicitly and also create the directory for more reliable builds.

Improve podman setup for build in latest ubuntu-latest

---

.github/workflows/ci.yaml
tox.ini

The GitHub runners no longer support 3.6, and 3.11 is the default python version nowadays.

Switch to SLE BCI language pack for unit testing

---

tests/test_openjdk.py
tests/test_openjdk_devel.py

This is a regression test for https://bugzilla.suse.com/show_bug.cgi?id=1206128
These tests will fail before https://github.com/SUSE/BCI-dockerfile-generator/pull/156 is merged and deployed.

Test the environment variable JAVA_HOME for openjdk & openjdk-devel

---

tests/test_openjdk.py

The regular expression wasn't formatted properly ('.' needs backslashes to match the literal dot rather than any character)
Plus run curl with -f to avoid downloading 404 urls.

Improve cassandra version extraction logic

---

bci_tester/data.py

`LABEL com.suse.supportlevel="l3"` is set by
https://build.suse.de/request/show/285987
- failure: https://openqa.suse.de/tests/10210286#step/_root_BCI-tests_metadata_podman/5

389ds is considered as L3 supported container

---

.github/workflows/ci.yaml

This is required before march 2023, see
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Migrate to GITHUB_OUTPUT

---

tests/test_metadata.py

.NET 7.0 images are already in registry.suse.com

Remove XFAIL for new dotnet images

---

README.rst
bci_tester/data.py
pyproject.toml
tests/test_metadata.py
tests/test_multistage.py

pytest_container can now inspect containers directly. Thereby we do not need to rely on skopeo for the tests anymore

Remove the need for skopeo

---

.github/workflows/ci.yaml

This key is a RSA 4096 bits state of affairs key:
pub   rsa4096 2023-03-22 [SC] [expires: 2025-05-30]
E2DF69DAD17CF92FB88C6E70306F981DB46B47C3
uid           devel:BCI OBS Project <devel:BCI@build.opensuse.org>
sig        306F981DB46B47C3 2023-03-22   [selfsig]
sig        CF0B928CDED64F3B 2023-03-22   [User ID not found]

Switch to new devel:BCI key

---

tests/test_distribution.py

This fixes https://github.com/SUSE/BCI-tests/issues/228

Remove usage of the alpine image to workaround docker rate limits

---

.github/workflows/ci.yaml

main branch is protected and we require PRs - so pre-merge CI should be enough, post-merge is just wasting resources

Skip CI on pushes to main branch

---

tox.ini

To avoid the `ModuleNotFoundError for 'ConfigParser'` we require `psycopg2` to be a more recent version.
* Related ticket: https://progress.opensuse.org/issues/128900
* Related failure (example): https://openqa.suse.de/tests/11072489#step/bci_test_podman/37
* Verification runs: [SLES15-SP4 aarch64](https://openqa.suse.de/tests/11073975) | [SLES12-SP5 x86_64](https://openqa.suse.de/tests/11074493)

Require psycopg2 version >= 2.9.6

---

tests/test_all.py

SLE_BCI repo is usually behind when containers are tested, so the "no-downgrade" trips. allow downgrades for now until situation is improved that the BCI repo is refreshed at the same time or before the containers are.

allow downgrade

---

tests/test_minimal.py

The size grew because of an ordering change in the rpm package installation which blew up Index.db. increase until we decide to drop the Index.db

Bump limits a bit

---

.github/workflows/ci.yaml

Uses this setting: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

Automatically cancel the tox integration tests on force pushes

---

tests/test_metadata.py

It got updated via https://github.com/SUSE/BCI-dockerfile-generator/pull/393

Fix the lifecycle URL in the metadata check

---

tests/test_all.py

Increase the timeout for zypper to prevent false positives on some slow architectures.
Example failues: [1](https://openqa.suse.de/tests/11265480#step/bci_test_podman/31) [2](https://openqa.suse.de/tests/11265479#step/bci_test_podman/37) [3](https://openqa.suse.de/tests/11265481#step/bci_test_podman/37)

Increase timeout for zypper

---

tests/test_ruby.py

It looks like the newest version of the sqlite3 gem can be installed from source, but on x86_64 and aarch64 there are prebuild binaries which fail to install. Thus we work around this by xfailing on x86_64 & aarch64 only.
This fixes https://github.com/SUSE/BCI-tests/issues/258 (well, sorta-kinda…)

xfail gem install sqlite3 only on x86_64 & aarch64

---

bci_tester/data.py

Introduce a new DEFAULT setting that is globally applied for testing if no more specific setting is being provided. Skip testing of application and language containers on 15.4 now that we have rolled over to 15.5

Test Language and App containers only on 15.5 by default

---

tests/test_postgres.py

Remove the md5 authentication method for RHEL7 because it was never working as expected and is not needed anymore.
* Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17364

Remove old authentications for RHEL7

---

tests/test_openjdk.py

cassandra is calling "getopt" which is coming from util-linux which might not be available (currently missing in opensuse/tumbleweed image)

Install util-linux for cassandra tests

---

bci_tester/data.py

Run `repository` test against already released base container.
- ticket: https://progress.opensuse.org/issues/132935

Add option to target released containers

---

setup.cfg

This avoids setuptools warnings in the CI logs about missing metadata

Provide slightly better setup.cfg metadata

---

tests/test_openjdk_devel.py

We therefore just concatenate stdout & stderr as we really just want to check whether the output is there.

openjdk:17 started printing `jshell>` to stderr

---

tests/test_distribution.py
tests/test_openjdk.py
tests/test_pcp.py
tests/test_php.py
tests/test_ruby.py

We don't want fails to be interpreted as success, so we need to run with --fail. and as the curj output isn't tested, we can use -s for consistency everywhere.

Always use curl -sf

---

tests/test_all.py

This helps to validate that we don't have unresolved dependencies in containers.

Add a zypper verify test

---

tests/test_metadata.py

We have frequently CI pipeline failures when we release a container for the first time, as it is checking for a reference being accessible that does not yet exist, and it would become accessible would the CI pipeline go through. This requires manual workarounds and overriding a release without proper testing, which isn't sensible.
As this is the only test that fails on an unreleased container, lets skip it in that case.

Skip testing reference when TARGET is not testing released containers

---

tests/test_metadata.py

Reverts SUSE/BCI-tests#292
@dirkmueller your PR deactivated that test completely. We run BCI-Tests nowhere with `TARGET=ibs-released`

Revert "Skip testing reference when TARGET is not testing released containers"

---

bci_tester/data.py

Disable the `go1.20-openssl` container as it was not yet released to the CR project.
* See https://suse.slack.com/archives/C02AF8LALDA/p1693401007506499?thread_ts=1693399023.295749&cid=C02AF8LALDA
* VR: http://duck-norris.qe.suse.de/tests/13498

Remove go1.20-openssl

---

bci_tester/data.py

Revert "Remove go1.20-openssl"

---

tests/test_go.py

Adds a softfailure for kured, which is currently broken on non-x86_64 systems.
* Verification run [aarch64](https://openqa.suse.de/tests/12016912#step/bci_test_podman/57)

Add softfailure for kured on non-x86_64

---

bci_tester/data.py
tests/test_all.py

These are 15.4 based containers, we shouldn't test them on 15.5

Fix testing for nodejs and postgresql 14 containers

---

tests/test_node.py

lodash switched froom node to bun (https://bun.sh/) which is no longer node compatible.

Remove lodash from node tests

---

tests/test_repository.py

These got included recently for the kernel-module-container and are ok to ship in the repository

Allowlist kernel-devel packages for test_repository

---

tests/test_all.py

oldstable is now on an image that doesn't have the issue with outdated gcc anymore.

Remove skipping of tests as we rotated the broken image out

---

tests/test_all.py

We have automated the release of SLE BCI repo, so downgrades should no longer be happening.

Disallow downgrade

---

bci_tester/util.py
tests/test_389ds.py
tests/test_all.py
tests/test_busybox.py
tests/test_dotnet.py
tests/test_fips.py
tests/test_git.py
tests/test_go.py
tests/test_helm.py
tests/test_init.py
tests/test_node.py
tests/test_openjdk_devel.py
tests/test_php.py
tests/test_postgres.py
tests/test_python.py
tests/test_ruby.py
tests/test_rust.py

check_output(..) is a shortcut for run_expect([0], ...).stdout

Use check_output() where possible

---

tests/test_repository.py

Although it has been built for aarch64 all the time, it only was delivered on aarch64 starting with SP5.

Test open-vm-tools on aarch64 only for SP5 and above

---

bci_tester/data.py
tests/test_all.py
tests/test_repository.py

In case the host is registered, it would otherwise use the registered channels

Restrict repository checks to the BCI repo

---

tests/test_node.py

chalk tests broke recently with no change on BCI side

Replace chalk with the more popular TypeScript tests

---

tests/test_repository.py

The python311 stack has complex dependencies that dnf is not able to evaluate properly.

Add more repoclosure false positives

---

tests/test_node.py

the tests are failing on aarch64 and ppc64le at least

Skip typescript on non-x86_64 hosts

---

tests/test_node.py

Don't use an empty tuple but a None object when building the test git repositories, to avoid using an empty tuple object with `to_pytest_param`.
This PR is a quickfix for e.g. https://openqa.suse.de/tests/12723318#step/_root_BCI-tests_node_docker/1

Fix node test container parametrize

---

tests/test_all.py

We switched to rust 1.73, so we no longer need this.

Revert "Ignore the incorrect rust1.72 expiration date"

---

tests/test_init.py

udev is considered too large as a dependency hog and unnecessary in containerized environments.

Verify that systemd containers are without udev installed

---

bci_tester/data.py
tests/test_repository.py

They don't have a SLE_BCI repo anymore, so the tests can never pass

Skip BCI repo specific tests on LTSS containers

---

.github/workflows/ci.yaml

We have now globally working credentials. so we don't need to login twice.
This reverts commit e70e2f20db13590233d1457c6621c5ad9152f541.

Revert "Add a specific login route for SP3 and SP4"

---

bci_tester/data.py
tests/test_all.py

This is a regression from 967db993afe3e1349538e9fde8610324e319406e which broke BCI repository pipeline

Create the marks for default_repos for Base containers again

---

tests/test_busybox.py

This enables testing for SP6, and since all supported/tested distros have busybox meanwhile, we don't need this anymore

Remove skip marks for busybox container

---

tests/test_kernel_module.py

dpdk is not supported s390x. ppc64le and arm64 need -Dplatform=generic as the cpu detection is broken on containers.

Fix kernel tests on non-x86_64

---

tests/test_rust.py

Remove serde from the rust testsuite temporarily until we updated to

---

tests/test_metadata.py

Prerequisite for: https://github.com/SUSE/BCI-dockerfile-generator/pull/823

Stop checking for the deprecated image-type label

---

tests/test_all.py

test_zypper_dup is a bit too agressive and on the other side misses cases. so we just validate that installing any of the additional packages would not cause a downgrade in the container.

replace test_zypper_dup_works with test_no_downgrade_on_install

---

bci_tester/fips.py
tests/test_base.py

This fixes the failing BCI base 15.6 tests.

Add 15.6 to the OpenSSL 3 list

---

tests/test_base.py

In this VR that fails https://openqa.suse.de/tests/13724362#step/_root_BCI-tests_base_/3 the size is 146 MiB

Increase the size a bit more for aarch64

---

tests/test_repository.py

ecryptfs-utils requires `(kmod(ecryptfs.ko) if kernel)` since SP6, but that cannot be resolved as we neither have the kernel nor `kmod(ecryptfs.ko)`

Add ecryptfs-utils to the repoclosure false positives for >= SP6

---

tests/test_base.py

In the new build the VR for aarch64 are failing because the size increased again to 149 MiB. 
https://openqa.suse.de/tests/13764074#step/_root_BCI-tests_base_/4
https://openqa.suse.de/tests/13764080#step/_root_BCI-tests_base_/4
`Base container size is 149.0 MiB for aarch64 (expected 142..147 MiB)`

Increase the size of aarch64 image

---

tests/test_php.py

Similarly to tumbleweed and basalt the versions have been upgraded which no longer provide that functionality

Stop checking for envvars on 15.6

---

tests/test_git.py

The `GIT_SERVER_CONTAINER` was implicitly relying on `bci/bci-base` resolving to `registry.suse.com/bci/bci-base`. This is implemented via `shortnames.conf`, but the respective change never made it into SLES 15 SP2. Instead we use the full URL and will use the latest bci-base for now.

Use the full registry url for the git server container

---

tests/test_all.py

The rust containers have found a new way to break the world. they have provide/obsoletes so the first time you run "zypper update", your handcrafted rust 1.75 container becomes a rust 1.77 container.
Catch this in the orphaned package check.

Avoid renames in the orphaned package test

---

tests/test_minimal.py

rpm regression was fixed, libpcre1 leftover was removed. Things should be good again.
This reverts commit a784749368dd9639036b1137e82d03f4d1633516.

Restore minimal container size checking to previous values

---

tests/test_node.py

- drop typescript, it takes ages to build, test and consumes insane amounts of memory
- resurect lodash test
- replace typescript with node-glob
- update docs

Node test adjustments

---

tests/test_all.py

zypper dup causes rustN to replace rustN-1, which we do not want to happen. Until https://bugzilla.suse.com/show_bug.cgi?id=1222959 is resolved, we xfail this test

xfail rust oldstable dup test

---

tests/test_all.py

This omits these huge json files from the testinfra log, which make the output of `pytest -vv` too big for any meaningful consumption

Pass output of dumpsolv -j via a temporary bind mount instead of via stdout

---

tests/test_base.py

the same fat libzypp update was released on SP5 like was introduced on SP6. we need to reduce dependencies somehow, but for now the pipeline needs to turn green

accept larger size for SP5 as well

---

tests/test_base.py

Due to inconsistent space reporting between docker and podman we limit the image size test to podman only.
* Context: https://github.com/containers/podman/issues/13777#issuecomment-1090133955
* Related failures: https://openqa.suse.de/tests/14103942#step/_root_BCI-tests_base_/2

Run test_base_size only on podman

---

tests/test_base.py

The update has also been introduced in the SP4 LTSS image, which causes many failures in [openQA](https://openqa.suse.de/tests/overview?result=failed&result=incomplete&result=timeout_exceeded&distri=sle&version=15-SP4&build=3.25_sles15-ltss-image&groupid=443). It is related to https://github.com/SUSE/BCI-tests/pull/458.  
VRs: https://openqa.suse.de/tests/14115056, https://openqa.suse.de/tests/14115057

accept larger size for 15.4 LTSS also

---

tests/test_repository.py

Spack is only available on x86_64 and aarch64.
Failing VR: https://openqa.suse.de/tests/14128383
Passing VR: https://openqa.suse.de/tests/14128446
Ref: https://build.opensuse.org/projects/openSUSE:Factory/packages/spack/files/spack.spec?expand=1

Spack only available for x86_64 and aarch64

---

tests/test_openjdk.py
tests/test_php.py

runtimes
Tumbleweed's tar is apparently leveraging some new syscalls that are blocked on old container runtimes like in the GitHub actions environment. So working around that by adding --no-same-permissions --no-same-owner
Also some small cleanup of the code.

Workaround cassandra unpacking issues on tumbleweed in old container

---

tests/test_base.py

this requires a working installation of /usr/lib(64)?/gconv

Test that iconv is working inside the base container

---

tests/test_all.py

libsolv-tools is no longer part of the default installed packages, so we need to pull it in for the test

Explicitly install libsolv-tools when we use it

---

tests/test_all.py
tests/test_repository.py

This should fix: https://openqa.suse.de/tests/14480268#step/_root_BCI-tests_repository_/5

add kernel-64kb-devel to allowed package names

---

tests/test_ruby.py

See: https://bugzilla.suse.com/show_bug.cgi?id=1225821

Force gem on SLE to use `--platform ruby` to install ffi

---

tests/test_repository.py

Test for the public cloud modules being installable as well

---

tests/test_go.py

Unfortunately this requires disabling tests on go < 1.22 because the new version requires it. this is only temporary so I think we can live with that.

Upgrade Helm to a version that doesn't have failing tests

---

tox.ini

See https://github.com/jd/tenacity/issues/471
[CI:TOXENVS] nginx,mariadb,tomcat

pin tenacity to < 8.4.0 as a hotfix for https://github.com/jd/tenacity/issues/471

---

.github/workflows/ci.yaml
tests/test_fips.py

For FIPS images we need to run the FIPS tests, even when those are running on non-FIPS hosts. Currently the FIPS tests are skipped on non-FIPS hosts. We need to add an exception for the FIPS images in BCI-Tests
- VR: http://10.146.5.131/tests/102

Run FIPS tests in non-FIPS hosts

---

tests/test_base.py
tests/test_minimal.py

We have stripped a bit further.

Reduce tumbleweed sizes

---

bci_tester/data.py
tests/test_base.py
tests/test_kernel_module.py
tests/test_openjdk.py
tests/test_php.py
tests/test_postgres.py
tests/test_python.py

This silences a slightly annoying warning in the test outpu

Remove container_from_pytest_param deprecated use

---

bci_tester/data.py

Switch the default OS_VERSION to 15.6

---

tox.ini

https://github.com/jd/tenacity/issues/471 is fixed so we can stop requiring tenacity < 8.4.0 now
[CI:TOXENVS] nginx,tomcat,mariadb

Unrestrict tenacity again

---

tests/test_repository.py

15.6 and newer has gotten the new libzypp stack which strips libsolv-tools as a default dependency. so we need to install it explicitly as it is no longer in the container by default.

Install libsolv-tools for the installcheck

---

tests/test_openjdk.py

One of the scripts calls free that is included in the procps package and no longer shipped by default
[CI:TOXENVS] openjdk

Install procps for cassandra tests

---

bci_tester/data.py

[CI:TOXENVS] python,ruby,389ds
CC @mgrossu

Roll over Python:3.6, Ruby:2.5 & 389ds to 15 SP6

---

tests/test_mariadb.py

Remove unused variables that are found by ruff 0.5.0

---

tox.ini

We don't need it installed, so this saves a few fractions of a second on every tox run.

skip installation of bci_tests module

---

tests/test_minimal.py

Rename the test that checks if rpm is present in minimal to `test_rpm_present_in_minimal`.

Renaming rpm present test in minimal

---

tests/test_all.py

This test compiles a go binary which performs a `http.Get`. So far, we implicitly assumed that glibc would export the same symbols across all service packs (the golang builder image can be based on a different service pack). This was recently invalidated with SP6, hence we disable CGO and thereby do not rely on glibc symbols anymore.
[CI:TOXENVS] all

Disable CGO for certificate fetching test

---

bci_tester/data.py

Fix variable name typo in assert message

---

bci_tester/data.py

The automatic setting of default marks only was working for development and application containers. restore it for base containers, as right now 15.5 is not in dev/app but it is in base containers.

Restore base container marks for 15.5

---

bci_tester/data.py

With 3360ec54739628dc773291ebd130bddd28a05e80 we can now remove the available_version overrides as they're now centrally defined

Apply default configured base available versions for base containers

---

tests/test_base.py

the actual container submitted to QA seems to be rounding up to a MB more. just bump it

bump the base-fips size a bit more

---

bci_tester/data.py

This is not a perfect solution as tomcat still works with the old url (it's build with `USER tomcat`), but it's better than before

Only replace the BCI_REPO url in containers where the file exists & is writeable

---

tests/test_all.py

jsc#PED-7256 has been addressed, reenable testing

Check kernel containers for absence of systemd again

---

tests/test_kiwi.py
tox.ini

Part of https://github.com/SUSE/BCI-tests/issues/536
Assumes test setup as - https://github.com/SUSE/BCI-tests/pull/537
---
steps used for local testing atm:
```
CONTAINER_RUNTIME=docker OS_VERSION=15.6 TARGET=custom BASEURL=registry.opensuse.org/devel/bci/sle-15-sp6/ tox -e kiwi
CONTAINER_RUNTIME=docker OS_VERSION=tumbleweed TARGET=custom BASEURL=registry.opensuse.org/devel/bci/tumbleweed/ tox -e kiwi
```

add tests for kiwi container image

---

tests/test_openjdk.py

This improves the test coverage here to ensure the packages are not forgotten.
Depends-On: https://github.com/SUSE/BCI-dockerfile-generator/pull/1349

Rely on awk and procps being installed in the openjdk containers

---

bci_tester/data.py
tests/test_metadata.py

Correct lifetime url for Tumbleweed

---

tests/test_fips.py

We cannot reliably install the necessary shared libraries into these containers and have to resort to ugly shared library copying hacks. These are potentially brittle and should be avoided.
This partially addresses https://github.com/SUSE/BCI-tests/issues/552

Don't build fips-test.c on containers without zypper

---

tests/test_metadata.py

In 15.6 we have updated it to build from dockerfile-generator so it now has the expected annotations.

Limit compat hacks for sle15-image to 15.5

---

bci_tester/data.py
pyproject.toml
tests/test_all.py
tests/test_metadata.py
tests/test_postfix.py
tox.ini

PR adds basic smoke test for postfix container image (re: https://github.com/SUSE/BCI-dockerfile-generator/pull/1046)
To test (with postfix container image built in linked PR 1046):
```
OS_VERSION=tumbleweed TARGET=custom BASEURL=registry.opensuse.org/home/defolos/bci/staging/tumbleweed/tumbleweed-1046/ tox -e postfix
OS_VERSION=15.6 TARGET=custom BASEURL=registry.opensuse.org/home/defolos/bci/staging/sle-15-sp6/6-1046/ tox -e postfix
```
```
OS_VERSION=15.5 TARGET=custom BASEURL=registry.opensuse.org/home/defolos/bci/staging/sle-15-sp5/5-1046/ tox -e postfix
/bin/sh -c \'ps -eo pid,cmd | grep \'"\'"\'^ *1 \'"\'"\' | sed \'"\'"\'s/^ *1 //\'"\'"\'\'', _stdout=b'', _stderr=b'/bin/sh: ps: command not found\n')
```
(missing `ps` command in `suse/sle15:15.5`)

WIP: add minimal smoke test for postfix container image

---

bci_tester/data.py

As of https://github.com/SUSE/BCI-dockerfile-generator/pull/1387 tomcat no longer contains zypper and hence needs to be removed from that list
[CI:TOXENVS] tomcat

Remove tomcat from the CONTAINERS_WITH_ZYPPER list

---

tests/test_repository.py

When f72a21307efe1b663c88f6f6872db83294a778bc was moved into test_repository it expanded the scope to all known zypper-root based containers. Not all of them are available in TARGET=ibs-cr which broke the repository tests. limit it back to base/base-fips container to unblock the release
[CI:TOXENVS] repository

Limit bci-repo tests to bci-base container

---

tests/test_all.py
tests/test_repository.py

Reverts SUSE/BCI-tests#571
Reminder to re-enable testing on all containers

Revert "Limit bci-repo tests to bci-base container"

---

tests/test_metadata.py

Tumbleweed disturl

---

tests/test_fips.py

Remove xfail that is no longer relevant

---

tests/test_repository.py

Reject packages with a SUSE-Firmware license in the BCI repo

---

tests/test_base.py

The libzypp and other improvements were backported to 15.6, so we can lower the sizes for base container again.
[CI:TOXENVS] base

Adjust for reduced 15.6/15.7 base image sizes

---

tests/test_base.py
tests/test_git.py
tests/test_metadata.py
tests/test_ruby.py

Unsorted list of lint fixes to get us above the threshold again

---

tests/test_metadata.py

Skip "SLE BCI advertisement" test for SAC containers

---

tests/test_metadata.py

Skip manifest test on ancient podman versions

---

tests/test_kiwi.py
tests/test_postfix.py

This is doing deep clones which takes forever. also the zypper installs prevent us from going with leaner base containers.

Remove use of git in tests

---

tests/test_kiwi.py
tests/test_postfix.py

Fixup curl change

---

tests/test_fips.py

Test for fips mode in gpgconf as well

---

tests/test_postfix.py

There is no zypper anymore in bci micro based containers.

Remove usage of zypper

---

tests/test_fips.py

Add testing for libica being in FIPS 140-3 mode

---

.github/workflows/ci.yaml
bci_tester/data.py
tests/test_all.py

This will not work properly before we have the SLE 15 SP7 BCI repo
This fixes https://github.com/SUSE/BCI-tests/issues/545

Enable SP7 testing

---

tests/test_postgres.py
tox.ini

This is obsolete (replacement is psycopg) and is a non-wheel binary extension which means the host needs to have postgresql-server-devel and python-devel installed, which is painful for tesing on minified distributions. Use a pure-python implementation instead.

Drop psycopg2 dependency

---

tox.ini

Run unit-tests for py 313

---

tests/test_repository.py

Ensure we never ship gcc-build

---

.github/workflows/ci.yaml
tox.ini

Ubuntu 22.04 is the only one with 3.10, we replace that with 24.04 which uses 3.12

Remove 3.10, add 3.12

---

bci_tester/data.py

Only test gcc 14 on sle15

---

bci_tester/data.py
tests/test_base.py

The ironbank base container is a fips container but actually called bci-base.

Fix handling of the ironbank base container

---

bci_tester/runtime_choice.py
tests/test_init.py

Due to worker unavailability we need to run ppc64le on emulated workers at the moment where the startup times are always larger than the threshold. Therefore there is no point in running this test at all on ppc64le at the moment.
[CI:TOXENVS] init

Temporarily skip startup test on ppc64le

---

bci_tester/data.py
tests/test_base.py

It has been replaced by 22 in both.

Remove node 20 from SP7 and Tumbleweed

---

tests/test_init.py
tests/test_mariadb.py
tests/test_postgres.py

Increase the timeouts for container startup temporarily due to the need of using emulated ppc workers.
[CI:TOXENVS] postgres,mariadb

Temporarily increase timeouts

---

bci_tester/data.py

Increase the timeout for the distribution container on ppc64le due to emulated workers being slow.
[CI:TOXENVS] distribution

Increase distribution image timeout on ppc64le

---

tests/test_mariadb.py

[CI:TOXENVS] mariadb
fixes: #504

Mariadb upgrade scenario testing

---

tests/test_node.py

Skip the glob repository test on PPC64 because it runs into timeouts on the emulated ppc64 workers.
* Related failure: https://openqa.suse.de/tests/15932882#step/bci_test_podman/60
[CI:TOXENVS] node

Skip glob repo on ppc64

---

.github/workflows/ci.yaml
tests/test_unit.py

Docstrings and ai exclude

---

tests/test_repository.py

The underlying errneous code stream lifecycle change in SP7 was fixed.
This reverts commit 5079686142a467cc8d9f050e0d9ee8b7fd69f70d.
[CI:TOXENVS] repository

Revert "xfail the codestream check"

---

bci_tester/selinux.py

os.listdir() on a nonexisting directory raises an exception. we can just test for directory and file existance instead.

Fix selinux check

---

bci_tester/data.py

Test python 3.13 on tumbleweed as well

---

tests/test_base.py

we switched to libcurl4-mini, adjust sizings.

Adjust sizings for the SLFO base container

---

bci_tester/data.py

Enable postgresql 17 testing on SLE15 SP6

---

bci_tester/data.py
tests/test_all.py

Repo url fix & remove xfail

---

tests/files/JCEProviderInfo.java
tests/files/Tcheck.java
tests/test_openjdk.py

Add new test to verify if security providers are set propperly after enabling FIPS mode in openJDK containers.
https://progress.opensuse.org/issues/167683
[CI:TOXENVS] openjdk

Added test for openJDK in FIPS mode. Fixes issue #614

---

bci_tester/data.py
tests/test_openjdk_devel.py

Add xfail for the openjdk-devel on ppc64le issue

---

bci_tester/data.py
pyproject.toml

Add bci-base-fips testing for 15.7, 16.0 and tumbleweed

---

tests/test_base.py

Adjust sizing of base container for 16.0

---

bci_tester/data.py
pyproject.toml

Adjust for newer /more stable helm container tagging

---

bci_tester/data.py
tests/test_all.py
tests/test_metadata.py

Enable AI containers for tox -e all

---

bci_tester/data.py
pyproject.toml

It recently updated from 10.1 to 10.2, we can just list `:latest` which is available and pointing to the right container.

Update to more stable tag for kiwi on tumbleweed

---

tests/test_metadata.py

This function was only introduced in python 3.9, but QA tests with python 3.6.

Avoid removesuffix()

---

tests/test_fips.py

The LTSS Fips images pull in the nvidia repo, which gpg key we haven't imported. This was accidentally removed by me in
https://github.com/SUSE/BCI-tests/pull/694#discussion_r1877882669

Add flag --gpg-auto-import-keys back to zypper in for FIPS gcrypt test

---

bci_tester/data.py
pyproject.toml
tests/test_all.py
tests/test_metadata.py
tests/test_python.py

Add testing for the python 3.9 SAC container

---

.github/workflows/ci.yaml

Expand the list of pre-cached hostnames with the new ones

---

tests/test_openjdk_devel.py

The jshell failure is only present on OpenJDK-devel 21, so we need to limit the softfailure also to just this Java version. See https://bugzilla.suse.com/show_bug.cgi?id=1221983#c1
[CI:TOXENVS] openjdk_devel
* [openjdk-devel-11](https://openqa.suse.de/tests/16183529#step/_root_BCI-tests_openjdk_/4)
* [openjdk-devel-17](https://openqa.suse.de/tests/16183530#step/_root_BCI-tests_openjdk_/4)
* [openjdk-devel-21](https://openqa.suse.de/tests/16183531#step/_root_BCI-tests_openjdk_/4)

Limit softfailure for bsc#1221983 to JDK21

---

bci_tester/data.py
tests/test_all.py

There is no perl anymore, and we also didn't check that the substitution actually happened.

Fix repository substitution for Tumbleweed

---

bci_tester/data.py

In https://github.com/SUSE/BCI-tests/pull/675 we added a new appcol python 3.11 container that uses the same test marker as the bci python 3.11 container. This makes it impossible to filter only one of these containers which now causes problems in QA on ppc64le and s390x because the application collection containers are not available on those architectures. This is a quick hotfix, that makes the QA jobs pass again, we must still fix the markers.

[appcol] Skip application collection containers on non aarch64 & x86_64

---

bci_tester/data.py
pyproject.toml
tests/test_ai.py
tests/test_metadata.py

Add initial milvus container testing

---

tests/test_kiwi.py

Switch kiwi testing to sp6

---

bci_tester/data.py

Enable more containers for SP7 based testing

---

tests/test_all.py

We have the LTSS container on a service pack still in general support, so a container-specific exclusion rather than merely a version based exclusion is needed.

Skip tests that depend on the BCI repo for the LTSS container

---

bci_tester/data.py
tests/test_metadata.py

Remove EOL containers (end of general support of SLE15 SP5)

---

tests/test_openjdk_devel.py

PR for https://github.com/SUSE/BCI-dockerfile-generator/pull/2109
[CI:TOXENVS] openjdk_devel

Don't check that jshell is the CMD on SLE 15 SP7+

---

bci_tester/data.py

Now that the LTSS container has finally passed QA, we can enable testing against the released container

Reenable SP5-ibs-released tests

---

bci_tester/data.py
pyproject.toml

Remove python 3.10 from testing

---

.github/workflows/ci.yaml
bci_tester/data.py

NodeJS22 should be initially be 15-SP6 based and only later on move to 15-SP7.
[CI:TOXENV] node

Make NodeJS 22 available for 15.6

---

tests/test_go.py

helm main branch is now helm 4 which dropped support for go older than 1.23

Update helm version to the latest release to test new golang-openssl

---

tests/test_base.py

Add test to validate availability of nogroup/nobody

---

bci_tester/data.py
pyproject.toml

Use latest tag for alertmanager on Tumbleweed
Related ticket: https://progress.opensuse.org/issues/176256

Use latest tag for alertmanager on Tumbleweed

---

.github/workflows/ci.yaml
README.rst
pre-commit-full.sh
pre-commit.sh

The check-mark test takes a long time. This commit decouples it and gives the suer the option to only do the formatting or also the check mark test in in the pre-commit hook.
* Follow-up of https://github.com/SUSE/BCI-tests/pull/734

Decouple check-marks from pre-commit hook

---

tests/test_metadata.py

Fix mariadb name after https://github.com/SUSE/BCI-dockerfile-generator/pull/2259

---

.github/workflows/ci.yaml

drop general 15.5 from testing (end of general support)

---

bci_tester/data.py
pyproject.toml
tests/files/kea-dhcp4.conf
tests/test_kea.py
tests/test_metadata.py
tox.ini

kea dhcp4 testing

---

.github/workflows/ci.yaml

probably a bit too early to enable it, so just as a test that can be manually triggered for now.

run all the jobs for sp7

---

tests/test_base.py

These binaries went multiple megabytes larger thanks to jsc#PED-11850

Accomodate for size increase of openssl and glibc on SP7/ppc64le

---

tests/test_base.py

Expand bci-base to 101 MB for 16.0/x86_64

---

tests/test_node.py

The build & test of typescript is quite flaky and takes ages to build. So far it hasn't caught a single bug.
[CI:TOXENVS] node

Drop Typescript build from node tests

---

bci_tester/data.py
pyproject.toml
tests/test_metadata.py
tests/test_valkey.py
tox.ini

Add valkey testing

---

bci_tester/data.py
pyproject.toml

The AI team decided to remove the 0.5 rolling tag in favor of a "0" tag instead.

switch ollama testing to more stable tag

---

bci_tester/data.py
pyproject.toml

Update the tag for open-webui to 0.5
* Related failures: e.g. https://openqa.suse.de/tests/17011027#step/bci_test_podman/32

Update Open-WebUI tag to 0.5

---

bci_tester/data.py

See https://confluence.suse.com/pages/viewpage.action?pageId=1749942754
[CI:TOXENVS] all

Fix OS_PRETTY_NAME for SLE 16

---

bci_tester/data.py
pyproject.toml

Switch to stable/oldstable for kubectl related images

---

tests/test_python.py

https://bugzilla.suse.com/show_bug.cgi?id=1232072

Test the packaged tox version as well

---

bci_tester/data.py
tests/test_metadata.py
tests/test_python.py

Keeping the test infrastructure in tact in case it gets revisited.

Drop SUSE AppCollection specific containers from testing

---

bci_tester/fips.py

Exclude sha1 from FIPS digests on Tumbleweed

---

tests/test_minimal.py

The fstring for exceeding the size was wrong.
* Related failure: https://openqa.suse.de/tests/17285579#step/_root_BCI-tests_minimal_/1
[CI:TOXENVS] minimal

Fix fstring

---

bci_tester/data.py
pyproject.toml

Add GCC 15 image to testing

---

tests/test_bind.py

Use `Union` instead of too new | syntax for Python 3.6

---

tests/test_init.py

DRY up the hostnamectl check

---

tests/test_all.py

Otherwise we're skipping too many tests.

only mark cpp13 as xfailed if it is actually installed in the container

---

bci_tester/data.py
pyproject.toml
tests/test_ai.py

These are kubernetes jobs, we can't really meaningfully test them

Add a noop testing for the suse-observability containers

---

.github/workflows/ci.yaml
bci_tester/data.py
tests/test_ai.py

Add AI tests for released containers

---

tests/test_metadata.py

This raises a CodeQL warning. even though it is harmless here as there isn't untrusted input, we can easily avoid it

avoid "in" matches for urls

---

bci_tester/fips.py
tests/files/fips-test.c
tests/test_base.py
tests/test_fips.py

Adjust tests for openssl 3.4/3.5 changes

---

.github/workflows/ci.yaml

Cache tox setups between runs

---

source/index.rst
source/setup.rst

Required for hand-over. Documents the currently used secrets according to my knowledge, but as @dirkmueller  added them all, I'd need further input.

Add docs about the CI & currently required secrets

---

tests/test_kernel_module.py

switch to a mirror of dpdk-kmod that isn't constantly down

---

tests/test_all.py

The check for additional repositories should only run on SLES hosts, where subscriptions are available.
Verification runs: [Leap (skipped)](https://duck-norris.qe.suse.de/tests/14859#step/_root_BCI-tests_all_/17) | [SLES](https://duck-norris.qe.suse.de/tests/14860#step/_root_BCI-tests_all_/17)
[CI:all]

Limit subscription repo tests to SLES hosts

---

bci_tester/fips.py
tests/test_unit.py

Drop unused function host_fips_supported()

---

tests/test_cosign.py

We finally started embedding the suse signing key in the suse cosign container, so we can just reference it directly.

Avoid depending on ftp.suse.com for verification

---

tests/test_metadata.py

Test for supportdate to be in the future

---

tests/test_metadata.py

use strptime for python 3.6+

---

tests/test_all.py

Ignore an exit code of 1 in "container-suseconnect lm"

---

bci_tester/data.py

Looking at the container data is really confusing because almost everything has a skipif(False) condition attached to it. we don't have to create it.

Don't create confusing marks

---

tests/files/kea-dhcp4.conf
tests/test_kea.py

Right now kea tests are failing as sometimes the client receives an ip address from an external dhcp server.
To avoid this issue, modified the dhcp client configuration to receive specific ip in the range offered by kea dhcp server.
[CI:TOXENVS] kea

Configure kea tests to request a specific ip in the range offered by kea server

---

.github/workflows/ci.yaml
tests/test_base.py
tests/test_fips.py

The BCI Base FIPS container for version 15-SP6 has compatibility with both OpenSSL 3 and OpenSSL 1.1, and so the latter must be checked.
For that, we should install `openssl-1_1` from the `Legacy Module 15-SP6`. And repeat the OpenSSL hashes test for it too in 15-SP6
[CI:fips,base]

Add OpenSSL 1.1 test to 15-SP6

---

tests/test_fips.py

Add test for the FIPS environment variables for containers, that do not allow other FIPS tests (e.g. SLES Micro-FIPS).
* Verification run: https://duck-norris.qe.suse.de/tests/14872 http://duck-norris.qe.suse.de/tests/14873 (unrelated failure)

Introduce test_fips_env

---

.github/workflows/ci.yaml
tox.ini

switch to pypi releases for pytest_container

---

bci_tester/data.py
pyproject.toml

Fix tests after distribution 3.0 upgrade

---

bci_tester/data.py

Fix expected updates URL for SLE 16.0, which dropped the concept of a Service Pack.
Related ticket: https://progress.opensuse.org/issues/176964
Fixes CI failure:
https://github.com/SUSE/BCI-tests/actions/runs/16009560314/job/45164070001?pr=867
```
FAILED tests/test_all.py::test_container_build_and_repo[local-bci/gcc:15 from registry.opensuse.org/devel/bci/16.0/containerfile/bci/gcc:15] - AssertionError: assert 'https://public-dl.suse.com/SUSE/Products/SLE-BCI/16.0/x86_64/product/' == 'https://updates.suse.com/SUSE/Products/SLE-BCI/16-SP0/x86_64/product/'
- https://updates.suse.com/SUSE/Products/SLE-BCI/16-SP0/x86_64/product/
?          ^ ^^^^                                  ^^^
+ https://public-dl.suse.com/SUSE/Products/SLE-BCI/16.0/x86_64/product/
```
Other failures are due to …

Fix expected updates URL for SLE 16.0

---

tests/test_gcc.py

this is one of the most frequently failing test because of occassional instability of ftpmirror.gnu.org. use our own hosted infrastructure instead

Switch fetching of hello example to opensuse

---

tests/test_kea.py
tox.ini

Fix for kea test not working on openQA
[Before](https://openqa.suse.de/tests/18393329#step/_root_BCI-tests_kea_/1)
[After](https://openqa.suse.de/tests/18405630)

Fix kea test not working on openQA

---

tests/test_ruby.py

Without this, tests fail with:
The last version of multi_json (>= 0) to support your Ruby &
RubyGems was 1.15.0. Try installing it with `gem install
multi_json -v 1.15.0`\n\tmulti_json requires Ruby version
>= 3.2. The current ruby version is 2.5.0.

Fix ruby 2.x tests failing on multi_json requiring a newer ruby

---

tests/test_python.py
tests/trainers/flask_hello_example.py

pipx requires its setup to be done as root, but it can run as a regular user once the setup is completed.
This test ensures that a pipx container application works as a non-root user.
[CI:TOXENVS] python,minimal

Add test for pipx with non-root user

---

bci_tester/data.py

Related ticket: https://progress.opensuse.org/issues/187371
Verification run: https://openqa.suse.de/tests/18803616

Add SLE 16.0 to RELEASED_SLE_VERSIONS

---

tests/test_fips.py

The bug has been resolved and the fix is already present in BCI 16.0 containers.

Remove bsc#1246541 xfail
