SUSE/BCI-tests

- test_go.py
This will allow us to test a very simple project, which uses
golang, prometheus, and kubernetes clients.
> Build kured as go example

- matryoshka_tester/data.py
- tox.ini
Dan updated the images and moved them to fcrozat's home.
This adapts the location of the containers, ensure
the latest containers are always fetched, and increase the
amount of containers to test.
> Update matryoshka urls and increase coverage

- .github/workflows/ci.yaml
This looked terrible.
This should clarify.
> Update gh actions job names

- matryoshka_tester/data.py
The python and node containers were using the wrong repositories.
> Fix container names

- .gitignore
- tox.ini
If we need that for openQA, as mentioned with Olaf.
> Add junit output

- .github/workflows/container-scan.yaml
This PR adds a simple container security scan using snyk.io, addressing the need mentioned in https://github.com/evrardjp/m8a-tests/issues/8
> [CI] Add container scan ci job

- .github/workflows/container-scan.yaml
Let's have another security scanner :wink:
> [CI] Add trivy vulnerability scan

- .github/workflows/ci.yaml
> Be gentle on gh actions

- README.md
- conftest.py
- matryoshka_tester/data/containers.json
- matryoshka_tester/helpers.py
- matryoshka_tester/parse_data.py
- test_base.py
- test_go.py
- test_init.py
- test_node.py
- test_openjdk-devel.py
- test_openjdk.py
- test_python.py
- tox.ini
The interesting part is happening in `test_init.py`.
> Systemd tests

- matryoshka_tester/data/containers.json
- test_python.py
Update the urls to the new containers in devel:BCI
> Update python tests

- test_metadata.py
- tox.ini
Relates to https://github.com/SUSE/BCI-tests/issues/57
> Add tests for the container metadata

- bci_tester/data.py
This fixes https://github.com/SUSE/BCI-tests/issues/106
> Include the container url in the test name

- tests/test_busybox.py
Add two new tests to busybox:
* Check for links in `/bin`
* Test a selection of basic commands for correct behaviour
Related ticket: https://progress.opensuse.org/issues/109812
> Improve busybox testing

- bci_tester/data.py
https://github.com/dcermak/pytest_container/issues/83
> Increase healthy check timeout for 389ds container

- tests/test_python.py
Some bci python versions 3.6 had errors checking the tensorflow version, for import issues.
http://openqa.suse.de/tests/8770107 
Added a direct check of the import and removed stdout redirection in the version check command
> python-tensorflow checks updated

- tests/test_all.py
- tests/test_pcp.py
Failures: https://openqa.suse.de/tests/8837435#
VR: https://openqa.suse.de/tests/8837881#
> Minor fixes for PCP image tests

- tests/test_busybox.py
- tests/test_python.py
Small simplifications and styling fixes for the python & busybox test modules
> Styling fixes

- tests/test_metadata.py
python:3.10 has been published, no need to xfail anymore
> Fix metadata tests

- format.sh
- tests/test_openjdk.py
- tests/trainers/java/threads_concurrency_and_sleep.java
VR: http://marvin5.arch.suse.cz/tests/449
> Add java test for threads

- tests/test_openjdk.py
- tests/trainers/java/time.java
VR: http://marvin5.arch.suse.cz/tests/716
> BCI Java: Java time module

- tests/test_openjdk.py
- tests/trainers/java/files_and_directories.java
VR: http://marvin5.arch.suse.cz/tests/702
> BCI Java: files and directories test

- tests/test_openjdk.py
- tests/trainers/java/garbage_collector.java
- tests/trainers/java/memory.java
http://progress.opensuse.org/issues/110689
VR: http://marvin5.arch.suse.cz/tests/756
> BCI java: memory allocation and garbage colleciton

- tests/test_openjdk.py
- tests/trainers/java/system_env.java
- tests/trainers/java/system_exit.java
- tests/trainers/java/system_properties.java
VR: http://marvin5.arch.suse.cz/tests/819
> BCI Java test for System module

- tests/test_openjdk.py
- tests/trainers/java/subprocesses.java
VR: http://marvin5.arch.suse.cz/tests/961
> BCI Java: subprocesses

- bci_tester/data.py
- pyproject.toml
Add the container definition for rust 1.62
> Add rust1.62

- bci_tester/data.py
- pyproject.toml
- tests/test_go.py
- tests/test_metadata.py
Add the container definitions for golang1.19
> Add golang1.19

- tests/test_ruby.py
see: https://bugzilla.suse.com/show_bug.cgi?id=1203692
> Mark gem install sqlite3 as broken

- tests/test_openjdk_devel.py
cc @grisu48 @jlausuch 
Looks like we can start publishing the openjdk-devel:17 image
> Remove xfail from the openjdk-devel:17 image

- tests/test_openjdk.py
Improve the BCI tests using a real application as cassandra DB.
https://progress.opensuse.org/issues/115043
VR: http://openqa.suse.de/tests/9622447
> BCI java test with cassandra

- bci_tester/data.py
- tests/test_metadata.py
> Test language & application stack containers only on latest os version

- bci_tester/data.py
- pyproject.toml
https://progress.opensuse.org/issues/122956
> Add rust 1.66 container

- tests/test_python.py
We want to give users the ability to use the SLE (FIPS compliant) version of openssl, so things like cryptography need to be installable  from source. Test for that.
> [python] Test installing complex pip modules from source

- bci_tester/data.py
pytest_container is now smart enough to do this by itself
> Remove deprecated default_entry_point=True

- tests/test_node.py
This fixes #213
cc @ricardobranco777
> Stop using deprecated option `npm config set shrinkwrap false`

- .github/workflows/ci.yaml
This way we can see sudden breakages outside PRs
> Run tests scheduled every other day

- .github/workflows/ci.yaml
- format.sh
- tests/test_python.py
> Remove old cruft and improve python tests

- .github/workflows/ci.yaml
We need to add the signkey of openSUSE:Factory to the gpg keys as well, so that we can pull registry.opensuse.org/opensuse/nginx for the php tests. And for that, we need a newer podman…
Requires #221
> Add openSUSE:Factory key

- bci_tester/data.py
- pyproject.toml
- ticket: https://progress.opensuse.org/issues/127628
> Add RUST 1.68 containers

- bci_tester/data.py
- pyproject.toml
- tests/test_metadata.py
This requires implementing ACC support status as well
> Test PostgreSQL 15

- .github/workflows/ci.yaml
This is used by the rust tests
> also cache index.crates.io

- tests/test_all.py
- tests/test_php.py
These are some implementation details that we were relying on that got changed yesterday.
> Pytest container fixes

- tests/test_distribution.py
- tests/test_pcp.py
- tests/test_php.py
@grisu48 can you please run a VR as well, whether the timeouts are long enough?
> Replace usage of localy installed curl with requests

- tests/test_all.py
- tests/test_metadata.py
> Remove a few outdated xfails

- tests/test_all.py
- tests/test_rust.py
only :oldstable is affected by bsc#1215834
> Enable testing for lifecycle on rust:stable

- tests/test_all.py
Breaks all current BCI test runs.
> Revert "Disallow downgrade"

- tests/test_repository.py
It does not exist on ppc64le and s390x
> Test open-vm-tools only on aarch64 and x86_64

- bci_tester/data.py
- pyproject.toml
Needed for the CI of #334 to pass
> Drop 389-ds:2.0, was only offered as part of SLE 15 SP4

- tests/test_fips.py
> Revert "Correct path of libz.so.1 on 15.5+"

- tests/test_repository.py
> Remove kernel-source-azure

- tox.ini
These pass without modifications
> Add py312 unit tests

- bci_tester/data.py
- tests/test_metadata.py
> Stop testing SP4 based language/app containers

- .github/workflows/ci.yaml
> Revert "Temporary use conmon from main Ubuntu repo until OBS project gets conmon 2.1.10"

- tests/test_base.py
increase the aarch64 size a bit so the base image builds
> bump aarch64 size

- tests/test_base.py
The 15-SP6 aarch64 container increased in size again.
> Yet another size increase

- .github/workflows/ci.yaml
The signing key has changed and publishing was half broken. so lets test for it so that we find it immediately
> Validate registry.suse.com containers as well

- tests/test_git.py
- tests/test_init.py
- tests/test_mariadb.py
- tests/test_openjdk.py
- tests/test_openjdk_devel.py
- tests/test_postgres.py
- tests/test_python.py
- tox.ini
Make pylint happy and bump the score to hopefully catch issues like https://github.com/SUSE/BCI-tests/commit/bb3bc7dfcfc633067fa43105f6b4605a501f573c by the CI
> Linting fixes

- tests/test_mariadb.py
The MariaDB image now provides the healthcheck.sh that can be used to check if the DB is properly initialized. Use this script to ensure containers are ready in the test.
Add tests to check if healthcheck.sh is working as expected.
Fixes #405.
> Use healthcheck.sh

- tests/test_base.py
apparently there is a small offset in the official qa workers
> Increase SP6/ppc64 by one MB

- tests/test_all.py
The self-obsoletion apparently fixed itself?
> Remove xfail from Rust oldstable

- tests/test_389ds.py
see https://github.com/389ds/389-ds-base/issues/6067 we now are required to pass in the basedn into all dsidm calls.
Luckily this is backward compatible with 2.x
> Use dsconf to initialize the baseroot and pass it for dsidm (Fixes #471)

- .github/workflows/ci.yaml
This allows to pin down what is slowing our CI.
> Enable pytest duration

- tests/test_git.py
Fixes the new test failures e.g.: https://github.com/SUSE/BCI-tests/actions/runs/9280400253/job/25534615581#step:13:2311
> [git] Fix ownership of /srv/git/project.git

- tests/test_node.py
This mimics https://github.com/expressjs/express/pull/5690
[CI:TOXENVS] node
> Remove deprecated npm settings

- bci_tester/data.py
- bci_tester/runtime_choice.py
- conftest.py
- pyproject.toml
- tests/test_389ds.py
- tests/test_all.py
- tests/test_base.py
- tests/test_build.py
- tests/test_busybox.py
- tests/test_dotnet.py
- tests/test_fips.py
- tests/test_gcc.py
- tests/test_git.py
- tests/test_helm.py
- tests/test_kernel_module.py
- tests/test_mariadb.py
- tests/test_metadata.py
- tests/test_minimal.py
- tests/test_multistage.py
- tests/test_openjdk.py
- tests/test_openjdk_devel.py
- tests/test_php.py
- tests/test_postgres.py
- tests/test_python.py
- tests/test_repository.py
- tests/test_ruby.py
- tests/test_rust.py
- tests/test_spack.py
- tests/test_tomcat.py
I merged the ruff PR too quickly without checking that isort is enabled
> Enable ruff isort

- conftest.py
> container_git_clone fixture: clone into workdir

- bci_tester/data.py
- pyproject.toml
- tests/test_base.py
- tests/test_metadata.py
> add a SP4 based LTSS/FIPS-140-3 container into testing

- tests/test_base.py
> Reduce tumbleweed size (it's ~ 99 MB now)

- tests/test_metadata.py
The test either does not work because osc is not installed, or it fails because osc is available but its dependency are not available inside the venv that the testsuite is running under. We can easily rewrite that with just using requests and avoiding the conflict with venvs
> Rewrite test_disturl_can_be_checked_out to not rely on osc

- tests/test_repository.py
> Check that uuidd is available

- bci_tester/data.py
- pyproject.toml
- tests/test_all.py
- tests/test_metadata.py
> Add kiwi container definition

- tests/test_python.py
> test pep517 wheel build (bsc#1202140)

- tests/test_kiwi.py
PR enables `test_kiwi_create_image()` for podman container runtime as well.
(earlier enabled only for `docker` assuming podman rootful mode wasn't allowed)
Verified – GitHub CI tests runs as root for podman
ref: https://github.com/SUSE/BCI-tests/blob/2de28a851adfd596fae5213c62472e7d01f0e043/.github/workflows/ci.yaml#L356-L357
---
Verified in CI, the kiwi tests executes successfully!
- Tumbleweed – https://github.com/SUSE/BCI-tests/actions/runs/10160098349/job/28095780381?pr=551#step:13:38
- 15.6 – https://github.com/SUSE/BCI-tests/actions/runs/10160098349/job/28095779927?pr=551#step:13:38
> enable `test_kiwi_create_image` for podman container runtime

- bci_tester/data.py
- pyproject.toml
> Bump 389ds version in Tumbleweed

- tests/files/fips-test.c
- tests/test_fips.py
> Fips sp6 digest error

- tests/test_kiwi.py
The skip within the function is too late as by that time the container is already started which fails. we need to skip outside the testing method.
> Skip kiwi tests as non-root podman runs

- tests/test_kiwi.py
this requires significantly more work to pass on non-x86
[CI:TOXENVS] kiwi
> Mark the kiwi image build test as x86 only

- tests/test_kernel_module.py
> Kernel module minor fixes

- bci_tester/data.py
> remove bci-base-fips for sp5

- .github/workflows/ci.yaml
- tests/test_fips.py
> use scc registration for fips ltss tests

- bci_tester/data.py
- pyproject.toml
> Bump kiwi version in Tumbleweed from 10.0 to 10.1

- tests/test_all.py
- tests/test_postfix.py
Follow up changes in tests, post merge of PR https://github.com/SUSE/BCI-dockerfile-generator/pull/1541
CI tests will give proper signal, when ^ PR is merged, and registry.opensuse.org have refreshed image tags.
> [postfix] update tests for changes in logging

- tests/files/fips-test-gnutls.c
> added checking for the FIPS Service Level Indicator bsc#1229728

- bci_tester/fips.py
- tests/files/fips-test-gnutls.c
- tests/test_fips.py
> FIPS tests added for gnutls library

- tests/test_repository.py
> Add boost_program_options to packages that we want to keep in the repo

- bci_tester/fips.py
- conftest.py
> Minor fixes

- tests/test_postfix.py
This works around the container not shipping ps
[CI:TOXENVS] postfix
CC @Priyankasaggu11929
> Obtain the process cmdline from /proc/ not via ps

- tests/test_fips.py
> Fips no xfail sp4

- bci_tester/selinux.py
- tests/test_kiwi.py
- tests/test_unit.py
> xfail kiwi image build on selinux enforcing hosts

- tests/test_fips.py
The "cleanup" in ed9a7fbdd7d39c4b9226bf5b7c4b565c28bae876 added globally executed mutable modification to the defined container marks by in-place mutating marks via "_marks += _non_fips_host_skip_mark", which causes every container in any test to be skipped, including non-fips tests. Revert the bulk of that cleanup and do a shallow copy instead.
> Avoid modifying the mutable version of container marks (Fixes #600)

- bci_tester/data.py
- pyproject.toml
> Add PostgreSQL 13/17 (tumbleweed only) testing

- tests/test_metadata.py
> Test for proper oci.image.base.name/digest annotation

- bci_tester/data.py
> Update PCP container version

- bci_tester/data.py
The version 17 was missing for the tomcat for SAC APPLICATION.
[CI:TOXENVS] tomcat
> Add sac-apache-tomcat-10-image:openjdk17

- tests/test_repository.py
> Test for codestream lifecycle information being correct (bsc#1227100)

- bci_tester/data.py
> Small cleanup

- bci_tester/data.py
- pyproject.toml
> Tomcat openjdk23

- tests/test_fips.py
Test Firefox in FIPS mode with a certificate which works in FIPS mode and one which does not (perhaps with sha1) You have to set the Kernel Parameter. to activate FIPS.
Tests passing:
`tests/test_fips.py::test_nss_firefox_cert[bci/bci-base-fips:15.6 from registry.opensuse.org/devel/bci/sle-15-sp6/containerfile/bci/bci-base-fips:15.6] PASSED [ 87%]`
> Add NSS Mozilla cert test for FIPS. Fixes #615

- bci_tester/data.py
- pyproject.toml
> Bump grafana version to 11 in Tumbleweed

- bci_tester/data.py
- pyproject.toml
- tests/test_cosign.py
- tests/test_metadata.py
- tox.ini
> Add cosign tests

- tests/test_fips.py
we are now enforcing fips mode for NSS, so we don't need to modify the mode. just check for the mode being correct.
Also fix password handling hang.
> Check whether the nssdb was created in fips mode in the fips containers

- .github/workflows/ci.yaml
- bci_tester/data.py
- pyproject.toml
- tests/test_metadata.py
- tests/test_python.py
https://bugzilla.suse.com/show_bug.cgi?id=1232537
> Add testing for python 3.13

- .github/workflows/ci.yaml
- bci_tester/data.py
> Enable kiwi tests on sle16

- bci_tester/data.py
- pyproject.toml
> Add testing for Tomcat 9 containers

- bci_tester/data.py
> Cosign 2.4 got released

- bci_tester/data.py
- pyproject.toml
- tests/test_ai.py
- tox.ini
> Add initial testing for the SUSE AI containers

- tests/test_git.py
Container startup is too fast for the emulated ppc64 workers.
* Related failure: https://openqa.suse.de/tests/15931383#step/bci_test_podman/59
[CI:TOXENVS] git
> Add startup delay of 1min to git healthcheck

- bci_tester/data.py
- tests/test_postgres.py
A higher increase of the timeouts.
[CI:TOXENVS] postgres
> Increase timeouts postgres

- tests/test_base.py
- tests/test_metadata.py
- tests/test_minimal.py
- tests/test_php.py
- tests/test_python.py
> Fix various typos in comments

- bci_tester/data.py
> Add node 22 testing for SP7

- bci_tester/data.py
- pyproject.toml
> Bump prometheus version to 3 in TW

- bci_tester/data.py
> Helm is now created as multistage dockerfile

- tests/test_fips.py
Add a check to verify that the FIPS mode is properly detected by gpgconf
https://progress.opensuse.org/issues/167683
> Add FIPS Vendor Affirmation Test for gcrypt

- tests/test_fips.py
> xfail gcrypt test on 15 sp3 due to bsc#1234366

- tests/test_tomcat.py
> [tomcat] stop needing curl for the tests

- .github/workflows/ci.yaml
- bci_tester/data.py
- pyproject.toml
- tests/test_base.py
> Enable testing for the SLE15 - SP5 LTSS base container

- tests/test_kiwi.py
> Skip kiwi tests on fips-enforcing hosts

- bci_tester/data.py
- conftest.py
- tests/test_all.py
- tests/test_distribution.py
- tests/test_dotnet.py
- tests/test_fips.py
- tests/test_go.py
- tests/test_init.py
- tests/test_metadata.py
- tests/test_minimal.py
- tests/test_openjdk.py
- tests/test_pcp.py
- tests/test_python.py
- tests/test_repository.py
> Switch to Ruff 2025 style (0.9.0)

- bci_tester/data.py
- pyproject.toml
- tests/test_metadata.py
> Add Ruby 3.4 testing (tumbleweed)

- bci_tester/data.py
> Correct git-container build type kiwi->docker

- tests/test_base.py
> Bump size for ppc64le a bit

- bci_tester/data.py
- pyproject.toml
> Bump spack version in SP7

- tests/test_python.py
> Use a webserver for tests that is under our control (bsc#1236833)

- tests/test_stunnel.py
The `test_stunnel_logging` test was implicitly assuming that the container is already up and running, as otherwise, there are no logs available yet. This worked on a powerful dev machine, but fails on slow cloud worker.
Therefore, we move the healtcheck function out of the individual tests and use it in all the stunnel test functions. This also reduces code duplication.
[CI:TOXENVS] stunnel
> Wait for the stunnel container to be up before checking its logs

- bci_tester/data.py
- pyproject.toml
[CI:TOXENVS] all
(not really testable on GitHub Actions)
> Bump Ollama version to 0.5

- bci_tester/data.py
- pyproject.toml
> Bump Grafana version to 10

- conftest.py
- tests/test_go.py
> Skip rancher on go mod

- bci_tester/data.py
- pyproject.toml
> Add Ruby 3.4 testing

- bci_tester/data.py
- pyproject.toml
> drop kubernetes 1.29 from Tumbleweed

- tests/test_repository.py
> Test that opencl-devel is available (jsc#PED-7838)

- bci_tester/data.py
- pyproject.toml
> Revert "Update Open-WebUI tag to 0.5"

- bci_tester/data.py
- pyproject.toml
[CI:TOXENVS] ai
VR: https://openqa.suse.de/tests/17049277
> Change open-webui tag to 0

- bci_tester/data.py
- pyproject.toml
- tests/test_ai.py
- tests/test_metadata.py
Submitting this PR to include the requested tag change in PR #752, as @chajain will not be able to continue working on that PR at the moment.
[CI:TOXENVS] ai
> Adding tests for AI pytorch container

- tests/test_init.py
See https://confluence.suse.com/pages/viewpage.action?pageId=1749942754
Also, add type hints and stop using `run_expect([0], cmd).stdout` instead use `check_output`
[CI:TOXENVS] init
> Fix OperatingSystemPrettyName check in hostnamectl for SLE 16

- bci_tester/fips.py
https://jira.suse.com/browse/PED-12198
[CI:TOXENVS] all
> Drop sha1 from the FIPS digests for SLE 16

- tests/test_init.py
> cosmetic changes in the Init module

- bci_tester/data.py
- pyproject.toml
- tests/files/db.blocked
- tests/files/named.conf
- tests/test_bind.py
- tests/test_metadata.py
- tox.ini
[CI:TOXENVS] bind
For https://github.com/SUSE/BCI-dockerfile-generator/pull/2364
> Add tests for the bind9 container image

- tests/test_minimal.py
> Update minimal sizing

- bci_tester/data.py
> Adjust for the next SLFO product rename

- bci_tester/data.py
- pyproject.toml
> Bump cosign version to 2.5

- bci_tester/data.py
> Add 15.7 to the released versions as we are entering GMC

- bci_tester/data.py
> Move bind container into CONTAINERS_WITHOUT_ZYPPER

- .github/workflows/ci.yaml
> Limit permissions of the GitHub token

- bci_tester/fips.py
- tests/test_base.py
> Openssl 3 5 fixes

- bci_tester/data.py
- pyproject.toml
- tests/test_ai.py
- tests/test_metadata.py
> Add test for AI open-webui-pipelines container

- bci_tester/data.py
> Check for L3 status on SP7

- bci_tester/data.py
- tests/test_all.py
- tests/test_fips.py
> Add a simple smoke test for container-suseconnect

- tests/test_bind.py
The domain is more resilient to outages. However, opensuse.org has multiple MX records and therefore we cannot compare just the first record from the bind container to the first from the host, we must compare them all.
> Switch bind test to opensuse.org

- bci_tester/data.py
- pyproject.toml
- tests/test_grafana.py
> Grafana tw

- bci_tester/data.py
- tests/test_metadata.py
> skip artifacthub tests on LTSS and AI containers

- tests/test_mariadb.py
> Test mariadb containers being run as non-root

- .github/workflows/ci.yaml
> run the mandatory 15.6 tests

- LICENSE
> Fix copyright statement

- tests/test_node.py
> Fix test_popular_npm_repos failure on s390x (bsc#1249029)

- bci_tester/data.py
> Switch to products/BCI

- tests/test_fips.py
On SLES < 15-SP6 libgcrypt will compute hashes for non-FIPS digests
(bsc#1229856). This will likely not be solved, because failing on those
digests is not considered a hard-requirement.
Therefore allow the libgcrypt hashes to compute older SLES versions, where the
behaviour of the library is to still compute hashes for those digests.
Still mark them as xfail.
Follow-up of https://github.com/SUSE/BCI-tests/pull/892
* Related ticket: https://progress.opensuse.org/issues/188511
* openQA Verification run: https://duck-norris.qe.suse.de/tests/15003#step/_root_BCI-tests_fips_/7
> Add xfail for bsc#1229856 for libgcrypt tests

- bci_tester/data.py
- pyproject.toml
Adds definition for the Postgres18 container for Tumbleweed.
[CI:TOXENVS] postgres
> Add postgres18
